#正则表达式
Regular:
  - "(C|c).*(N|n).*(M|m)"
#禁止开头如下词汇的聊天
AntiStart:
  - "蕾姆蕾姆"
#禁止结尾如下词汇的聊天
AntiEnd:
  - "了啦"
  - "poi"
  - "~~~"
#禁止包含如下词汇的聊天
AntiHave:
  - "SB"
  - "傻逼"
  - "操你妈"
  - "瞎骂"
  - "膜蛤"
  - "OP"
  - "管理员"
  - "服务器"
  - "操逼"
  - "麻痹"
  - "儿子"
  - "IP"
  - "地址"
  - "网址"
  - "http"
  - "www"
  - ".com"
  - "垃圾"
  - "智障"
  - "狗篮子"
#如果违反执行以下指令 不需要/
Command:
  - "tell %player% 请不要说脏话，你被惩罚禁言五秒"
  - "shock %player%"
#如果违反是否取消显示
Cancel: false
#脏话替换配置
Replace: "%player%是SB"
#是否给玩家发送警告
Warn: true
#警告信息设置 支持颜色符号
WarnMsg: "&c(%chat%)&e是脏话&b，&c你不能说脏话！"
#控制台监听
Console: true